---
abstract: 'Get elevation data from the USGS'
author:
  - 'Tom Wyant (wyant at cpan dot org)'
build_requires:
  Test::More: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-WebService-Elevation-USGS
no_index:
  directory:
    - inc
    - t
provides:
  Geo::WebService::Elevation::USGS:
    file: lib/Geo/WebService/Elevation/USGS.pm
    version: 0.010
requires:
  Carp: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Scalar::Util: 1.1
  XML::Parser: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Geo-WebService-Elevation-USGS
  license: http://dev.perl.org/licenses/
version: 0.010
