---
name: Geo-WebService-Elevation-USGS
version: 0.004
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Get elevation data from the USGS
license: perl
resources:
  license: ~
requires:
  Params::Util: 0.11
  SOAP::Lite: 0
build_requires:
  Test::More: 0.4
provides:
  Geo::WebService::Elevation::USGS:
    file: lib/Geo/WebService/Elevation/USGS.pm
    version: 0.004
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - inc
    - t
